id: ADBA471A5
base_file: fF31F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:38:18.659283
  last_modified_at: 2022-05-30 20:38:18.659290
